import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../models/settings_state.dart';

class AppLocalizations {
  static final Map<AppLocale, Map<String, String>> _translations = {
    AppLocale.russian: {
      'your_projects': 'Ваши проекты',
      'your_items_for_recoloring': 'Ваши предметы для перекраски',
      'no_projects': 'Нет проектов',
      'take_photo': 'Сделать фото',
      'gallery_permission_required': 'Требуется разрешение доступа к галерее',
      'error_selecting_image': 'Ошибка выбора изображения',
      'camera_requires_permission': 'Камера требует разрешения',
      'camera_error': 'Ошибка камеры',
      'camera_switch_unavailable': 'Переключение камеры недоступно',
      'result': 'Результат',
      'download': 'Скачать',
      'send': 'Отправить',
      'original': 'Оригинал',
      'recolor': 'Перекраска',
      'no_image': 'Нет изображения',
      'photo_saved_to_gallery': 'Фото сохранено в галерее',
      'no_gallery_save_permission': 'Нет разрешения на сохранение в галерею',
      'error_saving_to_gallery': 'Ошибка сохранения в галерею',
      'share_text': 'Посмотри на моё перекраска мебели!',
      'error_sending': 'Ошибка отправки',
      'ai_recoloring': 'AI перекраска...',
      'ai_recolor_error': 'Ошибка AI перекраски',
      'ai_error': 'Ошибка AI',
      'color_picked_with_eyedropper': 'Цвет выбран пипеткой',
      'palette': 'Палитра',
      'material': 'Материал',
      'easy': 'Лёгкая',
      'complex': 'Сложная',
      'eyedropper': 'Пипетка',
      'color_categories_red': 'Красный',
      'color_categories_orange': 'Оранжевый',
      'color_categories_green': 'Зеленый',
      'color_categories_purple': 'Фиолетовый',
      'color_categories_blue': 'Голубой',
      'color_categories_brown': 'Коричневый',
      'color_categories_gray': 'Серый',
      'color_categories_beige': 'Бежевый',
      'color_categories_pink': 'Розовый',
      'color_categories_metal': 'Под металл',
      'color_categories_black_white': 'Черный / Белый',
      'brown': 'Коричневый',
      'dark_brown': 'Тёмный',
      'light_brown': 'Светлый',
      'very_dark_brown': 'Очень тёмный',
      'muted_brown': 'Мутный',
      'gray': 'Серый',
      'dark_gray': 'Тёмный серый',
      'light_gray': 'Светлый серый',
      'very_dark_gray': 'Очень тёмный',
      'very_light_gray': 'Очень светлый',
      'beige': 'Бежевый',
      'antique_white': 'Античный белый',
      'wheat': 'Пшеничный',
      'cornsilk': 'Кукурузный',
      'khaki': 'Хаки',
      'pink': 'Розовый',
      'hot_pink': 'Горячий розовый',
      'pale_violet_red': 'Бледно-фиолетовый',
      'light_pink': 'Светло-розовый',
      'medium_violet_red': 'Средний красно-фиолетовый',
      'gold': 'Золото',
      'silver': 'Серебро',
      'bronze': 'Бронза',
      'brass': 'Латунь',
      'titanium': 'Титан',
      'stainless_steel': 'Нержавейка',
      'copper': 'Медь',
      'black': 'Черный',
      'white': 'Белый',
      'aging': 'Устаревание',
      'material_selection': 'Выбор материала',
      'wood': 'Дерево',
      'metal': 'Металл',
      'plastic': 'Пластик',
      'fabric': 'Ткань',
      'glass': 'Стекло',
      'leather': 'Кожа',
      'ceramic': 'Керамика',
      'concrete': 'Бетон',
      'no_texture': 'Без текстуры',
      'settings': 'Настройки',
      'language_russian': 'Русский',
      'language_english': 'English',
      'policy': 'Политика',
      'privacy_policy': 'Политика конфиденциальности',
      'terms_of_use': 'Политика использования',
      'app_version': 'Версия приложения',
      'light_mode': 'Лёгкая',
      'complex_mode': 'Сложная',
      'edit': 'Редактировать',
      'color': 'Цвет',
      'preview': 'Превью',
      'reset': 'Сброс',
      'save': 'Сохранить',
      'brush_size': 'Размер кисти:',
    },
    AppLocale.english: {
      'your_projects': 'Your Projects',
      'your_items_for_recoloring': 'Your items for recoloring',
      'no_projects': 'No projects',
      'take_photo': 'Take photo',
      'gallery_permission_required': 'Gallery access permission required',
      'error_selecting_image': 'Error selecting image',
      'camera_requires_permission': 'Camera requires permission',
      'camera_error': 'Camera error',
      'camera_switch_unavailable': 'Camera switch unavailable',
      'result': 'Result',
      'download': 'Download',
      'send': 'Send',
      'original': 'Original',
      'recolor': 'Recolor',
      'no_image': 'No image',
      'photo_saved_to_gallery': 'Photo saved to gallery',
      'no_gallery_save_permission': 'No permission to save to gallery',
      'error_saving_to_gallery': 'Error saving to gallery',
      'share_text': 'Check out my furniture recoloring!',
      'error_sending': 'Error sending',
      'ai_recoloring': 'AI recoloring...',
      'ai_recolor_error': 'AI recoloring error',
      'ai_error': 'AI error',
      'color_picked_with_eyedropper': 'Color picked with eyedropper',
      'palette': 'Palette',
      'material': 'Material',
      'easy': 'Easy',
      'complex': 'Complex',
      'eyedropper': 'Eyedropper',
      'color_categories_red': 'Red',
      'color_categories_orange': 'Orange',
      'color_categories_green': 'Green',
      'color_categories_purple': 'Purple',
      'color_categories_blue': 'Light blue',
      'color_categories_brown': 'Brown',
      'color_categories_gray': 'Gray',
      'color_categories_beige': 'Beige',
      'color_categories_pink': 'Pink',
      'color_categories_metal': 'Metallic',
      'color_categories_black_white': 'Black / White',
      'brown': 'Brown',
      'dark_brown': 'Dark',
      'light_brown': 'Light',
      'very_dark_brown': 'Very dark',
      'muted_brown': 'Muted',
      'gray': 'Gray',
      'dark_gray': 'Dark gray',
      'light_gray': 'Light gray',
      'very_dark_gray': 'Very dark',
      'very_light_gray': 'Very light',
      'beige': 'Beige',
      'antique_white': 'Antique white',
      'wheat': 'Wheat',
      'cornsilk': 'Cornsilk',
      'khaki': 'Khaki',
      'pink': 'Pink',
      'hot_pink': 'Hot pink',
      'pale_violet_red': 'Pale violet red',
      'light_pink': 'Light pink',
      'medium_violet_red': 'Medium violet red',
      'gold': 'Gold',
      'silver': 'Silver',
      'bronze': 'Bronze',
      'brass': 'Brass',
      'titanium': 'Titanium',
      'stainless_steel': 'Stainless steel',
      'copper': 'Copper',
      'black': 'Black',
      'white': 'White',
      'aging': 'Aging',
      'material_selection': 'Material selection',
      'wood': 'Wood',
      'metal': 'Metal',
      'plastic': 'Plastic',
      'fabric': 'Fabric',
      'glass': 'Glass',
      'leather': 'Leather',
      'ceramic': 'Ceramic',
      'concrete': 'Concrete',
      'no_texture': 'No texture',
      'settings': 'Settings',
      'language_russian': 'Russian',
      'language_english': 'English',
      'policy': 'Policy',
      'privacy_policy': 'Privacy Policy',
      'terms_of_use': 'Terms of Use',
      'app_version': 'App Version',
      'light_mode': 'Easy',
      'complex_mode': 'Complex',
      'edit': 'Edit',
      'color': 'Color',
      'preview': 'Preview',
      'reset': 'Reset',
      'save': 'Save',
      'brush_size': 'Brush size:',
    },
  };

  static String tr(BuildContext context, String key) {
    final locale = context.select<SettingsState, AppLocale>((s) => s.locale);
    return _translations[locale]?[key] ?? key;
  }
}
